<?php 

//Address Block Fields
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_5d23c05fcc904',
  'title' => 'GON Address',
  'fields' => array(
    array(
      'key' => 'field_5d264a83c0gsfdfgdsfda',
      'label' => 'Note:',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'You can edit contact information <a href="/wp-admin/admin.php?page=contact-info" target="_blank">here</a>',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ),
    array(
      'key' => 'field_5d23c05fd477a',
      'label' => 'Include Phone?',
      'name' => 'include_phone',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array(
      'key' => 'field_5d26432gdfsfgdb213c5',
      'label' => 'location handle',
      'name' => 'location_handle',
      'type' => 'text',
      'instructions' => '*optional. To display an address from a secondary location, enter the handle, as set in <a href="/wp-admin/admin.php?page=contact-info" target="_blank">\'GON Theme Settings > Contact Information\'</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/address',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
));

//iFrame fields
acf_add_local_field_group(array(
  'key' => 'group_5d23964e443ed',
  'title' => 'Google Maps iFrame',
  'fields' => array(
    array(
      'key' => 'field_5d264agsdsgfdgsvcx83c0gsfdfgdsfda',
      'label' => 'Note:',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => 'You can edit contact information <a href="/wp-admin/admin.php?page=contact-info" target="_blank">here</a><br><br><strong>Defaults:</strong><br><i>width:100%</i><br><i>height:350px</i>',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ),
    array(
      'key' => 'field_5d23baa5ffbcf',
      'label' => 'width',
      'name' => 'width',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d23bab8ffbd0',
      'label' => 'height',
      'name' => 'height',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_5d26432b213c5',
      'label' => 'location handle',
      'name' => 'location_handle',
      'type' => 'text',
      'instructions' => '*optional. To display an iframe from a secondary location, enter the handle, as set in <a href="/wp-admin/admin.php?page=contact-info" target="_blank">\'GON Theme Settings > Contact Information\'</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/iframe',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
));


endif;